### ISSUE TITLE
ScummVM 2.4.0 for Android version of RetroArch

### ISSUE THREAD

**Issue by GabiAle97** [DrUm78/scummvm#2]
Hi!

I've been looking for a way to update ScummVM core on RetroArch, since it's stuck on 2.1.1, and can't launch EFMI. Tested this fork, and builded the .so file, but wont work, neither on 32bits or 64 bits. It's succesfully installed, but when I load this core, nothing happens. Any ideas?

**Comment by DrUm78** [comment]
Hi. I compile mine for armv7a 32bit and Monkey 4 launches fine so not sure what your problem is.
You have to make sure first that you have the required file "/dists/engine-data/monkey4-patch.m4b" in your "extra" dir (but if you did not, you should have had an error message though). If that still does not work, then you have to contact the ScummVM team I guess.

**Comment by GabiAle97** [comment]
How do I compile this for armv7a 32? Sorry, I'm not familliar with this

**Comment by DrUm78** [comment]
The question is: what platform do you want to compile it for? If you tried my OPK, for sure it wouldn't work as it's ONLY the FunKey S device.

**Comment by GabiAle97** [comment]
If i'm not wrong, which is probably the case, since I want it on Android, I think it must be Unix, right? I've changed the "platform" variable to "unix" but still don't work

**Comment by GabiAle97** [comment]
Tried "android-armv7" and this shows up: Compiling detection.cpp...
/bin/sh: 1: arm-linux-androideabi-g++: not found
make: *** [Makefile:568: engines/scumm/detection.o] Error 127

**Comment by GabiAle97** [comment]
It's turning VERY difficult to me... Can you upload that .so you compiled? I really can't figure out how to do it myself

**Comment by DrUm78** [comment]
Nope, unix is not Android. You got this error because you do not have the proper toolchain installed, do you?
I don't have the setup to compile it for Android x64 but if your Android device is 32bit, so yes the .so file inside my opk should be compatible. Just extract it with SquashFS. iT's located in the "cores" folder.
Otherwise, diablodiab compiled some .so 3 weeks ago for Android here, you can try:
https://github.com/libretro/scummvm/issues/179#issuecomment-902153678

**Comment by GabiAle97** [comment]
Tried Diablodiab's fork too, but it's 2.3. In that version, it's laggy as hell, so it's not an option since 2.4 works so much better. My device is arm64, but using 32 version is not a problem if I use the RA32, right? Gonna try unzip that .opk and see what happens! Thank's a lot man.

**Comment by DrUm78** [comment]
Did not know that 2.3 worked worse than 2.4. Will bench it to compare so.
Hope that'll work for you anyway.

**Comment by DrUm78** [comment]
So you may need a arm64 version. Can you try diablodiab's arm64 one to confirm that? I close the ticket as there's no issue at all related to my repo here.
